remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
title: "Portfólio de Samuel Santos"
description: "Especialista em Ciência de Dados com foco em Geoprocessamento e Sustentabilidade"
